// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukawwqcuhuwjqvchsxru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrYXd3cWN1aHV3anF2Y2hzeHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0ODc2NTMsImV4cCI6MjA3MjA2MzY1M30._GjrjplvIR4_XnlWuyy6JC-cyUX8dN6oSU5df9VgMTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});